require("config.vimsettings")
require("config.lazy")
require("config.autocommands.jdtls")
require("config.autocommands.highlight-yanked")
require("config.autocommands.lsp-keymaps")
require("config.autocommands.lsp-jdtls-dap")
require("config.keymaps")
